// Code generated by mockery v2.42.0. DO NOT EDIT.

package editor

import mock "github.com/stretchr/testify/mock"

// Editor is an autogenerated mock type for the Editor type
type Editor struct {
	mock.Mock
}

// Edit provides a mock function with given fields: filename
func (_m *Editor) Edit(filename string) error {
	ret := _m.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEditor creates a new instance of Editor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Editor {
	mock := &Editor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
